# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python app on Ubuntu

on:
  push:
    branches: [ "GitHub-run-test" ]
  pull_request:
    branches: [ "GitHub-run-test" ]

permissions:
  contents: read
env:
  DISPLAY: 0
jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Tkinter for Ubuntu
      run: sudo apt-get install python3-tk
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install virtual envs and dependencies
      run: |
          python -m pip install --upgrade pipenv wheel
          
    - name: check run
      run: pipenv run *
