# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "GitHub-run-test" ]
  pull_request:
    branches: [ "GitHub-run-test" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv wheel
        #pip install flake8 pytest
        pip install -r requirements.txt

    - name: Build Linux executable
      run: |
          pipenv run pyinstaller --hidden-import=tkinter --name="HO_win" 
    - name: check run
      run: pipenv run hive_organizer.py
      #run: pipenv shell
